"""Update data table

Revision ID: 1dce6a5330c5
Revises: 644814965dd5
Create Date: 2025-04-23 14:24:30.706128

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dce6a5330c5'
down_revision = '644814965dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('waktu_peminjaman',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('pokok_pinjaman',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('total_tagihan',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('overdue',
               existing_type=sa.DATE(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('nomor_ec1',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('phone_ec2',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('phone_ec2',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('nomor_ec1',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('overdue',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('total_tagihan',
               existing_type=sa.String(length=255),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('pokok_pinjaman',
               existing_type=sa.String(length=255),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('waktu_peminjaman',
               existing_type=sa.String(length=255),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
