"""add label_case ke nomor_ticket

Revision ID: 23ce4df8dbc1
Revises: c33c463c01a6
Create Date: 2025-08-07 13:48:13.909259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ce4df8dbc1'
down_revision = 'c33c463c01a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('optional_1', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('optional_2', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('optional_3', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('optional_4', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('optional_4')
        batch_op.drop_column('optional_3')
        batch_op.drop_column('optional_2')
        batch_op.drop_column('optional_1')

    # ### end Alembic commands ###
