"""Update data table to link to User

Revision ID: 5f50b45ca734
Revises: 1dce6a5330c5
Create Date: 2025-04-28 11:59:39.730381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f50b45ca734'
down_revision = '1dce6a5330c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activity', schema=None) as batch_op:
        batch_op.drop_column('route')

    # ### end Alembic commands ###
