"""Update data table to link to User

Revision ID: 644814965dd5
Revises: 38030c202a32
Create Date: 2025-04-23 14:22:55.878459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '644814965dd5'
down_revision = '38030c202a32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('waktu_peminjaman',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('pokok_pinjaman',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_tagihan',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('overdue',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('overdue',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('total_tagihan',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('pokok_pinjaman',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('waktu_peminjaman',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
