"""Update data table to link to User

Revision ID: bae2b3c45778
Revises: 230a59fedd65
Create Date: 2025-04-23 14:12:25.465922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bae2b3c45778'
down_revision = '230a59fedd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('overdue',
               existing_type=sa.DATE(),
               type_=sa.String(length=15),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('overdue',
               existing_type=sa.String(length=15),
               type_=sa.DATE(),
               existing_nullable=True)

    # ### end Alembic commands ###
